# Generated by Django 3.2.3 on 2021-07-26 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpostapp', '0013_auto_20210726_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
